name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello"
      - name: Print Ubuntu Version
        run: echo "Ubuntu Version $(lsb_release -r -s)"
      - name: Print Commit SHA
        run: echo "Commit SHA ${{ github.sha }}"
