name: Custom Actions

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello"
      - name: Print Ubuntu Version
        run: echo "Ubuntu Version $(lsb_release -r -s)"
      - name: Print Commit SHA
        run: echo "Commit SHA ${{ github.sha }}"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: sisapers/part1
      - name: Print Files in Repo
        run: ls -1
      - name: Run test.sh
        run: bash test.sh
  

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Print First Name
        run: echo "First Name $FIRST_NAME"
        env:
          FIRST_NAME: John
      - name: Print Last Name
        run: echo "Last Name $LAST_NAME"
        env:
          LAST_NAME: Doe
      - name: Print Phone Number
        run: echo "Phone Number $PHONE_NUMBER"
        env:
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
